### ISSUE TITLE
Can't mix AuthElement and OptionalAuthElement

### ISSUE THREAD

**Issue by takiri** [t2v/play2-auth#148] opened 2015-07-24 12:57 UTC
Hi,

I'd like to extend both AuthElement and OptionalAuthElement in a same trait but I can't since methods 'proceed' and 'restore' are defined in the two of them, leading to ambiguity.

Thanks

**Comment by gakuzzzz** [comment] 2015-07-31 16:44
Hi,

mmm, It's a bit difficult...
Can you use AuthActionBuulders instead of AuthElement and OptionalAuthElement ?

example) https://github.com/t2v/play2-auth/blob/master/sample/app/controllers/builder/Messages.scala
doc in japanese)  https://github.com/t2v/play2-auth/blob/master/README.ja.md#actionfunction-としての利用


regards

**Comment by david-bouyssie** [comment] 2015-08-04 07:41
Seems to be a less straightforward solution for us.

Here is our current workaround:
<pre>
// Define a trait that can be used to define controllers with Auth capabilities
trait PWXAuthController extends PWXStackableController with PWXAuthConfig with AuthElement {
  val authorityKey = AuthorityKey
}

trait PWXLoginLogoutController extends PWXStackableController with PWXAuthConfig with LoginLogout {
  
  // BEGIN OF FORK OF OptionalAuthElement (workaround because it can't be mixed with AuthElement) 
  case object PWXAuthKey extends RequestAttributeKey[User]
  
  override def proceed[A](req: RequestWithAttributes[A])(f: RequestWithAttributes[A] => Future[SimpleResult]): Future[SimpleResult] = {
    implicit val (r, ctx) = (req, StackActionExecutionContext(req))
    restoreUser2 recover {
      case _ => Option.empty
    } flatMap {
      case Some(u) => super.proceed(req.set(PWXAuthKey, u))(f)
      case None => authenticationFailed(req)
    }
  }
  
  implicit def loggedInOpt[A](implicit req: RequestWithAttributes[A]): Option[User] = req.get(PWXAuthKey)
  
  private def restoreUser2(implicit request: RequestHeader, context: ExecutionContext): Future[Option[User]] = {
    val userIdOpt = for {
      cookie <- request.cookies.get(cookieName)
      token <- CookieUtil.verifyHmac(cookie)
      userId <- idContainer.get(token)
    } yield (token, userId)
    userIdOpt map { case (token, userId) =>
      resolveUser(userId) andThen {
        case Success(Some(_)) => idContainer.prolongTimeout(token, sessionTimeoutInSeconds)
      }
    } getOrElse {
      Future.successful(Option.empty)
    }
  }
  
  // END OF FORK OF OptionalAuthElement
  
}

</pre>

Our PWXLoginLogoutController extends our PWXAuthController (which extends itself AuthElement). This allows to have both loggedIn and loggedInOpt methods available in the PWXLoginLogoutController trait. This is clearly a workaround but we are using this since a year without any bug. The problem is that we have to maintain this workaround with the evolution of the play2-auth plugin.

Your suggested solution seems to be more robust but also more complicated to implement. So we will wait for a more detailed and translated documentation before beginning to implement it ;)

Thank you very much !

**Comment by gakuzzzz** [comment] 2015-10-06 07:35
thanks for workaround, @david-bouyssie

Since the reaction does not, I close this issue.
If there are any questions, please use gitter https://gitter.im/t2v/play2-auth :)

**Closed by gakuzzzz** 2015-10-06 07:35 UTC

**Comment by david-bouyssie** [comment] 2015-10-06 07:49
I have to say that it's not a very clean workaround because it's a fork of your code and I have to update my workaround for every new release of play2-auth.
This was the case yesterday when I updated my dependency to the latest version.
So if you have a better solution our team is still interested.

**Comment by gakuzzzz** [comment] 2015-10-13 04:46
@david-bouyssie

the stackable-controller that play2-auth use in `AuthElement` and `OptionalAuthElement` compose action by every trait.
If you controll action composition by every method, you can use ActionBuilder that play2 standard action composition system.
And play2-auth provides some ActionBuilders, you can use AuthActionBuilders instead AuthElement.

thanks
